default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: wallet_api_base_development

test:
  <<: *default
  database: wallet_api_base_test

production:
  <<: *default
  database: wallet_api_base_production
  username: wallet_api_base
  password: <%= ENV['WALLET_API_BASE_DATABASE_PASSWORD'] %>
